### ISSUE TITLE
Filtering tests

### ISSUE THREAD

**Issue by parkhabit** [fac-13/vith-Mixtape#52]
It looks like these tests [here](https://github.com/fac-13/vith-Mixtape/blob/master/logic.test.js#L105-L120) aren't really doing what they're supposed to. Please tell me if I'm wrong, but when I run the tests this is what I get back 
![screen shot 2018-03-16 at 10 45 19](https://user-images.githubusercontent.com/16639540/37516775-35cf5874-2907-11e8-912e-c82942c09f01.png)
Can you write this test so that you show that the array has been filtered?

**Comment by helenzhou6** [comment]
I think it may be working, since when I run:
<img width="717" alt="screen shot 2018-03-16 at 11 32 42" src="https://user-images.githubusercontent.com/25727036/37518620-d10e12ca-290d-11e8-8144-4840172e0429.png">
I get this:
<img width="654" alt="screen shot 2018-03-16 at 11 33 26" src="https://user-images.githubusercontent.com/25727036/37518629-de374318-290d-11e8-83e1-864b47f314da.png">

Whilst this code:
<img width="733" alt="screen shot 2018-03-16 at 11 34 06" src="https://user-images.githubusercontent.com/25727036/37518657-fb20c3b4-290d-11e8-804b-188928386342.png">
Output is: 
<img width="664" alt="screen shot 2018-03-16 at 11 34 12" src="https://user-images.githubusercontent.com/25727036/37518659-01e0eb66-290e-11e8-926c-0f5af7bcc7cc.png">

So what I think is happening with the latter is the object is being turned into a string (and thus becomes `[object, Object]` etc when you use `console.log`, but the `deepEquals` test should be functioning 👍

**Comment by helenzhou6** [comment]
Sorry misread this - should have fixed it now 😅
